[font]
size = 16

[font.normal]
family = "JetbrainsMono Nerd Font"

[window.padding]
x = 0
y = 0

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "W"
mods = "Control|Shift"
action = "Quit"
