- name: Add asdf plugin for cmake
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf plugin-add cmake"
  register: asdf_add_nodejs
  failed_when: asdf_add_nodejs == 2

- name: Install cmake
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf install cmake {{ item }}"
  loop: "{{ cpp_cmake_versions }}"

- name: Set global cmake version
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf global cmake {{ cpp_cmake_global_version }}"
