- name: Add asdf plugin for conan
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf plugin add conan"
  register: asdf_add_conan
  failed_when: asdf_add_conan == 1

- name: Install conan
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf install conan {{ cpp_conan_version }}"

- name: Set global conan version
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf global conan {{ cpp_conan_version }}"

# - name: Remove existing conan profiles
#   file:
#     name: "{{ ansible_env.HOME }}/.conan/profiles"
#     state: absent

# - name: Install conan config profiles
#   command: "conan config install 

