- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: redhat.yml
  when: ansible_os_family == "Redhat"

- import_tasks: cmake.yml
  when: cpp_install_cmake

- import_tasks: conan.yml
  when: cpp_install_conan

- import_tasks: vcpkg.yml
  when: cpp_install_vcpkg
