tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "koekeishiya/formulae"

cask "dbeaver-community"
cask "docker"
# cask "iterm2"
cask "postman"
cask "slack"
cask "spotify"
cask "visual-studio-code"
# cask "wezterm"
# cask "alacritty" --no-quarantine

cask "font-jetbrains-mono-nerd-font"

brew "bat"
brew "cmake"
brew "cppcheck"
brew "cpplint"
brew "eza"
brew "fd"
brew "fzf"
brew "git"
brew "gh"
brew "glow"
brew "go"
brew "gnu-sed"
brew "htop"
brew "include-what-you-use"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "llvm"
brew "maven"
brew "ninja"
brew "meson"
brew "neofetch"
brew "neovim"
brew "nvm"
brew "openjdk"
brew "pyenv"
brew "ripgrep"
brew "rustup-init"
brew "skhd"
brew "terraform"
brew "tmux"
brew "tmuxinator"
brew "wget"
brew "zig"
brew "zlib"
brew "zoxide"
brew "yabai"
