require("options")
require("autocmds")
require("keymaps")

require("utils")
require("colorscheme")
require("statusline")
require("treesitter")
require("lsp")
require("completion")
require("formatting")
require("fzf")
require("git")
require("explorer")
require("testing")
require("debugging")
