- name: Install (yum)
  yum:
    name: "{{ item }}"
    update_cache: yes
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ rhel_packages }}"

- name: Remove (yum)
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: absent
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ rhel_remove_packages }}"
