- name: Add asdf plugin
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf plugin-add golang"
  register: asdf_add_golang
  failed_when: asdf_add_golang == 1

- name: Install
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf install golang {{ item }}"
  loop: "{{ golang_versions }}"

- name: Set global version 
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf global golang {{ golang_global_version }}"
