---
# Core setup across all playbooks

- name: Update Apt
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Update Yum
  become: true
  yum:
    update_cache: true
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

