- name: Install zsh
  package:
    name: zsh
  tags:
    - install
    - dotfiles
    - zsh

- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  become: true
  tags:
    - zsh

- name: Check for oh-my-zsh
  stat:
    path: '{{ ansible_env.HOME }}/.oh-my-zsh'
  register: oh_my_stat
  tags:
    - install
    - dotfiles
    - zsh

- name:
  shell: 'curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > {{ ansible_env.HOME }}/.oh-my-installer && chmod +x {{ ansible_env.HOME }}/.oh-my-installer && {{ ansible_env.HOME }}/.oh-my-installer'
  when: oh_my_stat.stat.exists == False
  become: yes
  become_user: root
  tags:
    - install
    - dotfiles
    - zsh

- name: Install zsh-autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh/plugins/zsh-autosuggestions'
  tags:
    - install
    - dotfiles
    - zsh

- name: Stow zsh config
  shell: "cd {{ ansible_env.HOME }}/dotfiles && stow zsh"
  tags:
    - install
    - dotfiles
    - zsh
