- name: Check if zsh is installed
  shell: command -v zsh
  register: zsh_exists
  ignore_errors: yes

- name: Install zsh
  when: zsh_exists is failed
  become: yes
  become_user: root
  package:
    name: zsh

# - name: Change shell to zsh
#   become: yes
#   become_user: root
#   shell: usermod --shell /usr/bin/zsh

- name: Check for oh-my-zsh
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: omz_stat

- name: Install oh-my-zsh
  when: omz_stat.stat.exists == False
  shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'

- name: Stow zsh
  shell: cd ~/dotfiles && stow zsh
