- name: Add asdf plugin
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf plugin-add nodejs"
  register: asdf_add_nodejs
  failed_when: asdf_add_nodejs == 2

- name: Install
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf install nodejs {{ item }}"
  loop: "{{ nodejs_versions }}"

- name: Set global version
  command: "{{ ansible_env.HOME }}/.asdf/bin/asdf global nodejs {{ nodejs_global_version }}"
