---
- name: Install tmux
  become: yes
  become_user: root
  package:
    name: tmux
  tags:
    - install
    - dotfiles
    - tmux


- name: Stow tmux config
  shell: 'cd {{ ansible_env.HOME }}/dotfiles && stow tmux'
  tags:
    - install
    - dotfiles
    - tmux
