local function map(mode, lhs, rhs, opts)
  opts = opts or {}
  opts.silent = opts.silent ~= false
  vim.keymap.set(mode, lhs, rhs, opts)
end

map({ "n", "x" }, "j", "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true })
map({ "n", "x" }, "<down>", "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true })
map({ "n", "x" }, "k", "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true })
map({ "n", "x" }, "<up>", "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true })

map("x", "<", "<gv")
map("x", ">", ">gv")

map("n", "<esc>", "<cmd>nohlsearch<cr><esc>")

map("t", "<esc><esc>", "<c-\\><c-n>")
map("n", "<leader>tt", "<cmd>vertical term<cr>", { desc = "Terminal (vertical)" })
map("n", "<leader>tT", "<cmd>horizontal term<cr>", { desc = "Terminal (horizontal)" })

map("n", "<leader>w", "<cmd>write<cr>")
map("n", "<leader>q", "<cmd>quit<cr>")
map("n", "<leader>qq", "<cmd>qa<cr>")
map("n", "<leader>bd", "<cmd>bd<cr>", { desc = "Buffer delete" })
map("n", "<leader>bl", "<cmd>b#<cr>", { desc = "Buffer alternate" })

map("n", "<leader><space>", "<cmd>Pick files<cr>", { desc = "Files" })
map("n", "<leader>/", "<cmd>Pick grep_live<cr>", { desc = "Grep live" })
map("n", "<leader>:", "<cmd>Pick history<cr>", { desc = "History" })
map("n", "<leader>,", "<cmd>Pick buffers<cr>", { desc = "Buffers" })
map("n", "<leader>sd", "<cmd>Pick diagnostic<cr>", { desc = "Diagnostics" })
map("n", "<leader>sD", "<cmd>Pick diagnostic scope='current'<cr>", { desc = "Diagnostics (buffer)" })
map("n", "<leader>sh", "<cmd>Pick help<cr>", { desc = "Help" })
map("n", "<leader>sk", "<cmd>Pick keymaps<cr>", { desc = "Keymaps" })
map("n", "<leader>sm", "<cmd>Pick marks<cr>", { desc = "Marks" })
map("n", "<leader>sr", "<cmd>Pick resume<cr>", { desc = "Resume" })
map("n", "<leader>ss", "<cmd>Pick lsp scope='document_symbol'<cr>", { desc = "Symbols (buffer)" })
map("n", "<leader>sS", "<cmd>Pick lsp scope='workspace_symbol'<cr>", { desc = "Symbols (workspace)" })

map("n", "<leader>gs", "<cmd>Git<cr>", { desc = "Status" })
map("n", "<leader>gc", "<cmd>Git commit<cr>", { desc = "Commit" })
map("n", "<leader>gC", "<cmd>Git commit --amend<cr>", { desc = "Commit amend" })
map("n", "<leader>gd", "<cmd>Gdiffsplit<cr>", { desc = "Diff split" })
map("n", "<leader>gD", "<cmd>Git diff<cr>", { desc = "Diff" })
map("n", "<leader>gb", "<cmd>Git blame<cr>", { desc = "Blame" })
map("n", "<leader>gl", "<cmd>Pick git_commits<cr>", { desc = "Log (pick)" })
map("n", "<leader>gL", function()
  MiniExtra.pickers.git_commits({ path = vim.fn.expand("%") })
end, { desc = "Log buffer (pick)" })
map("n", "<leader>gB", "<cmd>Pick git_branches<cr>", { desc = "Branches (pick)" })
map("n", "<leader>gf", "<cmd>Pick git_files<cr>", { desc = "Files (pick)" })
map("n", "<leader>gh", "<cmd>Pick git_hunks<cr>", { desc = "Hunks (pick)" })
map("n", "<leader>gH", function()
  MiniExtra.pickers.git_hunks({ path = vim.fn.expand("%") })
end, { desc = "Hunks buffer (pick)" })
map("n", "<leader>gp", "<cmd>Git push<cr>", { desc = "Push" })
map("n", "<leader>gP", "<cmd>Git pull<cr>", { desc = "Pull" })
map("n", "<leader>go", "<cmd>lua MiniDiff.toggle_overlay()<cr>", { desc = "Diff overlay" })
