return {
  "nvim-treesitter/nvim-treesitter",
  event = { "BufReadPost", "BufNewFile" },
  dependencies = {
    "nvim-treesitter/nvim-treesitter-textobjects",
  },
  build = ":TSUpdate",
  cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
  keys = {
    { "<c-space>", desc = "Increment Selection" },
    { "<bs>", desc = "Decrement Selection" },
  },
  lazy = vim.fn.argc(-1) == 0,
  init = function(plugin)
    require("lazy.core.loader").add_to_rtp(plugin)
    require("nvim-treesitter.query_predicates")
  end,
  opts = {
    highlight = { enable = true },
    indent = { enable = true },
    ensure_installed = {
      "bash",
      "c",
      "cmake",
      "cpp",
      "diff",
      -- "dockerfile",
      "git_config",
      "gitcommit",
      "git_rebase",
      "gitignore",
      -- "gitattributes",
      -- "go",
      -- "gomod",
      -- "gowork",
      -- "gosum",
      "http",
      "ini",
      -- "java",
      -- "javascript",
      "json",
      -- "jsonc",
      "json5",
      "lua",
      "luadoc",
      "luap",
      "make",
      "markdown",
      "markdown_inline",
      "meson",
      "ninja",
      "printf",
      "python",
      "query",
      "regex",
      -- "ron",
      "rst",
      -- "rust",
      "sql",
      -- "tsx",
      -- "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
      -- "zig",
    },
    incremental_selection = {
      enable = true,
      keymaps = {
        init_selection = "<c-space>",
        node_incremental = "<c-space>",
        scope_incremental = false,
        node_decremental = "<bs>",
      },
    },
  },
  config = function(_, opts)
    require("nvim-treesitter.configs").setup(opts)
  end,
}
