local M = {}

local icons = {
  dap = {
    Stopped             = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
    Breakpoint          = " ",
    BreakpointCondition = " ",
    BreakpointRejected  = { " ", "DiagnosticError" },
    LogPoint            = ".>",
  },
  diagnostics = {
    Error = " ",
    Warn  = " ",
    Hint  = " ",
    Info  = " ",
  },
  git = {
    added    = " ",
    modified = " ",
    removed  = " ",
  },
  kinds = {
    Array         = " ",
    Boolean       = "󰨙 ",
    Class         = " ",
    Codeium       = "󰘦 ",
    Color         = " ",
    Control       = " ",
    Collapsed     = " ",
    Constant      = "󰏿 ",
    Constructor   = " ",
    Copilot       = " ",
    Enum          = " ",
    EnumMember    = " ",
    Event         = " ",
    Field         = " ",
    File          = " ",
    Folder        = " ",
    Function      = "󰊕 ",
    Interface     = " ",
    Key           = " ",
    Keyword       = " ",
    Method        = "󰊕 ",
    Module        = " ",
    Namespace     = "󰦮 ",
    Null          = " ",
    Number        = "󰎠 ",
    Object        = " ",
    Operator      = " ",
    Package       = " ",
    Property      = " ",
    Reference     = " ",
    Snippet       = " ",
    String        = " ",
    Struct        = "󰆼 ",
    TabNine       = "󰏚 ",
    Text          = " ",
    TypeParameter = " ",
    Unit          = " ",
    Value         = " ",
    Variable      = "󰀫 ",
  },
}

local text_icons = {
  dap = {
    Stopped             = { "> ", "DiagnosticWarn", "DapStoppedLine" },
    Breakpoint          = "B ",
    BreakpointCondition = "C ",
    BreakpointRejected  = { "R ", "DiagnosticError" },
    LogPoint            = ".>",
  },
  diagnostics = {
    Error = "X ",
    Warn  = "! ",
    Hint  = "? ",
    Info  = "i ",
  },
  git = {
    added    = "[+] ",
    modified = "[~] ",
    removed  = "[-] ",
  },
  -- kinds = {
  --   Array         = " ",
  --   Boolean       = "󰨙 ",
  --   Class         = " ",
  --   Codeium       = "󰘦 ",
  --   Color         = " ",
  --   Control       = " ",
  --   Collapsed     = " ",
  --   Constant      = "󰏿 ",
  --   Constructor   = " ",
  --   Copilot       = " ",
  --   Enum          = " ",
  --   EnumMember    = " ",
  --   Event         = " ",
  --   Field         = " ",
  --   File          = " ",
  --   Folder        = " ",
  --   Function      = "󰊕 ",
  --   Interface     = " ",
  --   Key           = " ",
  --   Keyword       = " ",
  --   Method        = "󰊕 ",
  --   Module        = " ",
  --   Namespace     = "󰦮 ",
  --   Null          = " ",
  --   Number        = "󰎠 ",
  --   Object        = " ",
  --   Operator      = " ",
  --   Package       = " ",
  --   Property      = " ",
  --   Reference     = " ",
  --   Snippet       = " ",
  --   String        = " ",
  --   Struct        = "󰆼 ",
  --   TabNine       = "󰏚 ",
  --   Text          = " ",
  --   TypeParameter = " ",
  --   Unit          = " ",
  --   Value         = " ",
  --   Variable      = "󰀫 ",
  -- },
}

if vim.g.have_nerd_font then
M = icons
else
M = text_icons
end

return M
