- name: Setup local workstation
  hosts: local
  roles:
    - role: packages
      tags:
        - packages
    - role: zsh
      tags:
        - zsh
    - role: tmux
      tags:
        - tmux
    - role: asdf
      tags:
        - asdf
    - role: tools
      tags:
        - tools
    - role: nvim
      tags:
        - nvim
    - role: python
      tags:
        - python
    - role: nodejs
      tags:
        - nodejs
    # - role: golang
    #   tags:
    #     - golang
    - role: cpp
      tags:
        cpp
